set_night_mode:
  name: Set Night Mode
  description: Zapne nebo vypne noční režim (Night Mode) na soundbaru.
  fields:
    entity_id:
      description: ID entity Media Playeru
      required: true
      example: media_player.soundbar_192_168_1_10
      selector:
        entity:
          domain: media_player
    night:
      description: true = zapnout, false = vypnout
      required: true
      example: true
      selector:
        boolean: {}